### ISSUE TITLE
Support rooms/talks with and without online Q&A

### ISSUE THREAD

**Issue by kittykat** [matrix-org/conference-bot#191]
At the moment, Q&A is enabled for all devrooms and talks of specific length.

Some FOSDEM devrooms may not take online questions at all, and some talks may also not take online questions so we need to be able to disable to announcements for specific devrooms or specific talks

Can we use the tags in the pretalx API to get this information?

**Comment by reivilibre** [comment]
I suggest we use a pretalx 'tag' for this; it seems like the most natural choice.

I should note that they don't seem to be available in the 'frab-compatible' XML and JSON views presented on the pretalx site (looking at another pretalx conference).

According to pretalx API documentation they should be available in the API. They might be private to the organisers so that might be why.

**Comment by Half-Shot** [comment]
The pentabarf schedule provides this to us https://fosdem.org/2024/schedule/xml
